### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by Eric-Tran** [UltimateAngular/ultimate-angular-master-seed#2]
Hello, 

I'm getting error after running npm start. I updated and downloaded all dependencies and ran npm install, following your set-up requirements.

vendor.js:39766 Uncaught ReferenceError: require is not defined
vendor.js:4640 Uncaught Error: [$injector:modulerr] Failed to instantiate module root due to:
Error: [$injector:modulerr] Failed to instantiate module components due to:
Error: [$injector:modulerr] Failed to instantiate module components.auth due to:
Error: [$injector:modulerr] Failed to instantiate module firebase due to:
Error: [$injector:nomod] Module 'firebase' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=firebase
    at http://localhost:4000/js/vendor.js:68:12
    at http://localhost:4000/js/vendor.js:2082:17
    at ensure (http://localhost:4000/js/vendor.js:2006:38)
    at module (http://localhost:4000/js/vendor.js:2080:14)
    at http://localhost:4000/js/vendor.js:4617:22
    at forEach (http://localhost:4000/js/vendor.js:321:20)
    at loadModules (http://localhost:4000/js/vendor.js:4601:5)
    at http://localhost:4000/js/vendor.js:4618:40
    at forEach (http://localhost:4000/js/vendor.js:321:20)
    at loadModules (http://localhost:4000/js/vendor.js:4601:5)

**Comment by hon4ymoon** [comment]
![capture](https://cloud.githubusercontent.com/assets/4240986/18575591/a7df78f2-7c03-11e6-973e-cefd81ffa02c.PNG)

**Comment by Eric-Tran** [comment]
Hon4ymoon try running sudo npm start, or sudo gulp that should fix your problem. However once gulp loads I get the problem above where require is not defined in the vendor.js file.

**Comment by Eric-Tran** [comment]
Seems like my other projects using babel was interfering. Disabling babel cache or removing the babel.json file in my root system directory solved the problem.

**Comment by timothylombrana** [comment]
@Eric-Tran I have the same problem, how did you disable babel cache?

**Comment by Eric-Tran** [comment]
Looks like the issue is actually still there..my app is stuck on the initial "loading..." Screen with require is not defined. Can anyone help solve this?

**Comment by toddmotto** [comment]
Pushed a fix for this, it was due to `firebase.js` new version which swapped everything out for CommonJS "require" syntax for browser usage which completely broke the bundle as we're not using require in the browser. So I've hard coded the version number here for a temporary fix so I can look into using the CJS format or new distribution format: https://github.com/toddmotto/ultimate-angular-master-seed/commit/22011371623f01b3fbd6c072eb50a252615758ce

**Comment by Eric-Tran** [comment]
Thanks it's working now! 👍
