### ISSUE TITLE
Trouble with npm run deploy command 

### ISSUE THREAD

**Issue by vincecampanale** [UltimateAngular/ultimate-angular-master-seed#4]
Hi Todd, 
Great course! One small issue -- when I do the `npm run deploy` command, it doesn't seem to work correctly. Google hasn't turned up with much useful information, but I'm going to keep searching. Thought I'd ask here as well. 
Is this a version issue or something else?
<img width="885" alt="screen shot 2017-03-12 at 11 41 22 pm" src="https://cloud.githubusercontent.com/assets/15335197/23840656/668627d8-077d-11e7-86eb-c5de772afd86.png">

**Comment by aaburgos4** [comment]
hey @vincecampanale, I am having this issue as well. Did you ever resolve it?

**Comment by vincecampanale** [comment]
@aaburgos4 I did not unfortunately -- still haven't finished the Angular 1.x course. Luckily I was just going through it for kicks and not for work or something.

**Comment by bhanu721** [comment]
hey @aaburgos4, i too had faced the same problem. For me I had forgot to remove the ';' at the end of the module declaration in 'auth.module.js' before adding config part.
