### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Vortilion** [UltimateAngular/ultimate-angular-master-seed#6]
Hi,

unfortunately there seems to be an error when trying to follow the instructions for setting up this project. If I try to npm install, it throws several python errors:

`gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\GITROOT\angularjspro_final-project\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\GITROOT\angularjspro_final-project\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\GITROOT\angularjspro_final-project\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\GITROOT\\angularjspro_final-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\GITROOT\angularjspro_final-project\node_modules\node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<name>\AppData\Roaming\npm-cache\_logs\2018-08-17T12_44_20_429Z-debug.log`

**Comment by Vortilion** [comment]
If I install python manually, I'm getting following errors:

[2018-08-17T13_01_31_931Z-debug.log](https://github.com/UltimateAngular/ultimate-angular-master-seed/files/2297263/2018-08-17T13_01_31_931Z-debug.log)
`

**Comment by Vortilion** [comment]
following steps seemed to do the trick:

1. Open cmd as admin and enter `npm install -g windows-build-tools`
2. Change version of **gulp-sass** in package.json to from "^2.3.2" to "^3.0.0"
3. still in admin cmd go to project root and enter `npm install`

Running the server via `npm start` still won't work though, nothing happens after showing the "Loading..." text in the browser. The console says:

`Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode

https://errors.angularjs.org/1.7.3/$injector/modulerr?p0=ng&p1=Error%3A%20%5B%24injector%3Astrictdi%5D%20function(%24provide)%20is%20not%20using%20explicit%20annotation%20and%20cannot%20be%20invoked%20in%20strict%20mode%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.7.3%2F%24injector%2Fstrictdi%3Fp0%3Dfunction(%2524provide)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A138%3A12%0A%20%20%20%20at%20Function.annotate%20%5Bas%20%24%24annotate%5D%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A4283%3A17)%0A%20%20%20%20at%20injectionArgs%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A5080%3A36)%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A5113%3A18)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A5010%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A5020%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A387%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A5000%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A4917%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fvendor.js%3A1941%3A20)`

I'm disappointed honestly, I thought I could work with the final project, but it seems it already stops at the setup. :-(

**Comment by Vortilion** [comment]
It looks like the error comes from the `ng-strict-di` directive, even though it should not raise any errors. Theres no DI used yet, so why does it bother with it?

**Comment by EnricoMassone** [comment]
@Vortilion hi, I'm facing your same exact errors. Did you manage to solve it ?

**Comment by Vortilion** [comment]
> @Vortilion hi, I'm facing your same exact errors. Did you manage to solve it ?

Hi! Yeah, it is in my last comment: remove the „ng-strict-di“ directive. This was also Todds answer when I asked him via twitter. It’s not a real answer to why its in the code to start with when the solution is „just remove it“...

**Comment by EnricoMassone** [comment]
@Vortilion thank you very much, it works

**Comment by EnricoMassone** [comment]
For all the ones having the same error discussed here, the steps to fix are the followings:

- run a command line with admin privileges at the project root (at the same level of the `package.json` file)
- run the command `npm install -g windows-build-tools`
- change the version of the dev dependency `gulp-sass` from `^2.3.2` to `^3.0.0`
- remove the directive `ng-strict-di` from the `index.html` file
- run the command `npm install`
- run the command `npm start` to launch the app

Hope this helps
